# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 7d01187f0f80cc5498ebdf73c5eedb805745c1eee2242fdb1c731cbd54471f76e8e12b8325b09bea59a822b782ebf596224bd9ff8d3282dbfbb59990cd4c6c0b

test:
  secret_key_base: de95ccb056570544513e9ffaf2d11a4d3be1790d98f9f5a537c5ee8ec1c34af7521f530c64140f53dcb4d79a99a61e35ade24aabd4286ca6ec6859f47e91e68c

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
